// Owner methods below are explicit business doubles linked ONLY into this
// diagnostic EXE. Production Server is compiled unchanged, without test macros.
#include "a_save_dispatch_ipc.h"
#include "a_save_dispatch_mailbox.h"
#include <cstdio>
#include <cstring>
#include <string>
#include <thread>
namespace ip=a_save_dispatch_ipc;namespace mb=a_save_dispatch_mailbox;namespace fs=checkpoint_fresh_save;
static void need(bool ok,const char*why){if(!ok){printf("FAIL %s\n",why);fflush(stdout);ExitProcess(90);}}
static SRWLOCK ownerLock=SRWLOCK_INIT;
static a_save_user_owner::Report ownerReport{};
static mb::Mailbox*retainedMailbox=nullptr;
static unsigned ownerStops=0,badStopOrder=0,hostAccepts=0;
namespace a_save_user_owner {
Owner::Owner():p_(nullptr){}
void Owner::Snapshot(Report&r)noexcept {AcquireSRWLockShared(&ownerLock);r=ownerReport;ReleaseSRWLockShared(&ownerLock);}
void Owner::Stop()noexcept {mb::Report r{};retainedMailbox->Snapshot(r);AcquireSRWLockExclusive(&ownerLock);++ownerStops;badStopOrder+=!r.stopped;ownerReport.stopped=1;ReleaseSRWLockExclusive(&ownerLock);}
}
static bool permit(void*,const fs::Request&q,const unsigned char*)noexcept{return q.generation>=1&&q.generation<=2&&q.period==q.generation;}
static void executionStop(void*p)noexcept{static_cast<mb::Adapter*>(p)->Stop();}
static bool io(HANDLE h,bool write,void*p,DWORD size){auto*b=static_cast<unsigned char*>(p);DWORD at=0;while(at<size){DWORD n=0;BOOL ok=write?WriteFile(h,b+at,size-at,&n,nullptr):ReadFile(h,b+at,size-at,&n,nullptr);if(!ok||!n)return false;at+=n;}return true;}
static ip::Request request(ip::Op op,std::uint64_t seq,unsigned gen=0){ip::Request r{};r.magic=ip::Magic;r.version=ip::Version;r.opcode=unsigned(op);r.sequence=seq;r.secret[0]=0x5A;if(gen){r.binding[0]=static_cast<unsigned char>(gen);r.save.generation=gen;if(op==ip::Op::Submit){r.save.room_epoch=7;r.save.period=gen;r.save.room_id[0]=1;r.save.year=203;r.save.month=8;r.save.day=static_cast<unsigned char>(gen==1?11:21);r.save.force=12;r.save.ruler=666;sprintf_s(r.save.filename,"mp%08x.s14",gen);}}return r;}
static bool response(HANDLE h,const ip::Request&q,ip::Header&head,std::vector<unsigned char>&body){if(!io(h,false,&head,sizeof head))return false;need(head.magic==ip::Magic&&head.version==ip::Version&&head.opcode==q.opcode&&head.sequence==q.sequence&&head.payload_size>=sizeof(ip::Snapshot)&&head.payload_size<20*1024*1024&&!memcmp(head.binding,q.binding,32),"wire response identity");body.resize(head.payload_size);return io(h,false,body.data(),head.payload_size);}
static HANDLE number(const wchar_t*s){return reinterpret_cast<HANDLE>(_wcstoui64(s,nullptr,10));}
static int client(int argc,wchar_t**argv){need(argc==9,"client args");const std::wstring mode=argv[2],pipeName=argv[3];const auto parent=wcstoul(argv[4],nullptr,10);HANDLE drop=number(argv[5]),closed=number(argv[6]),finish=number(argv[7]);(void)argv[8];
 auto until=GetTickCount64()+5000;HANDLE pipe=INVALID_HANDLE_VALUE;while(GetTickCount64()<until){pipe=CreateFileW(pipeName.c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,OPEN_EXISTING,0,nullptr);if(pipe!=INVALID_HANDLE_VALUE)break;Sleep(5);}need(pipe!=INVALID_HANDLE_VALUE,"child connects actual named pipe");ULONG server=0;need(GetNamedPipeServerProcessId(pipe,&server)&&server==parent,"kernel server PID identity");
 std::uint64_t seq=0;const bool normal=mode==L"normal";ip::Header head{};std::vector<unsigned char>body;
 if(normal){for(unsigned gen=1;gen<=2;++gen){auto q=request(ip::Op::Submit,++seq,gen);need(io(pipe,true,&q,sizeof q)&&response(pipe,q,head,body)&&head.status==unsigned(ip::Status::Ok),"real Submit transaction accepted");ip::Snapshot snap{};memcpy(&snap,body.data(),sizeof snap);need(snap.generation==gen&&!snap.stopped&&!snap.owner_error&&!snap.capabilities,"same generation Owner snapshot required by frozen client");
   bool copied=false;for(unsigned retry=0;retry<100&&!copied;++retry){q=request(ip::Op::Copy,++seq,gen);need(io(pipe,true,&q,sizeof q)&&response(pipe,q,head,body),"real Copy transaction");if(head.status==unsigned(ip::Status::NotReady)){Sleep(5);continue;}need(head.status==unsigned(ip::Status::Ok),"Copy status");
    need(body.size()==sizeof(ip::Snapshot)+checkpoint_fresh_save_packet::HeaderBytes+4,"encoded packet exact length");const auto*packet=body.data()+sizeof(ip::Snapshot);need(!memcmp(packet,"S14FSV01",8),"real packet encoder magic");const unsigned char payload[]={static_cast<unsigned char>(gen),2,3,4};unsigned char hash[32]{};need(native_storage_read::Sha256(payload,4,hash)&&!memcmp(packet+checkpoint_fresh_save_packet::HeaderBytes,payload,4)&&!memcmp(packet+checkpoint_fresh_save_packet::HeaderBytes-32,hash,32),"client verifies transmitted bytes and SHA");char output[40]{};sprintf_s(output,"normal-%u.packet",gen);FILE*f=nullptr;need(fopen_s(&f,output,"wb")==0&&f,"owned received packet output");need(fwrite(packet,1,checkpoint_fresh_save_packet::HeaderBytes+4,f)==checkpoint_fresh_save_packet::HeaderBytes+4&&fclose(f)==0,"persist actual wire packet for frozen Python decoder");copied=true;}
   need(copied,"artifact delivered");}
  auto q=request(ip::Op::Stop,++seq);need(io(pipe,true,&q,sizeof q)&&response(pipe,q,head,body)&&head.status==unsigned(ip::Status::Ok),"Stop response drains before EOF");
 }else {auto q=request(ip::Op::Submit,++seq,1);need(io(pipe,true,&q,sizeof q),"send pending Submit");if(mode.find(L"disconnect")!=std::wstring::npos)need(WaitForSingleObject(drop,5000)==WAIT_OBJECT_0,"await requested pipe-only disconnect");else {const bool replied=response(pipe,q,head,body);need(!replied||head.status!=unsigned(ip::Status::Ok),"shutdown cannot report accepted Save");}}
 CloseHandle(pipe);SetEvent(closed);need(WaitForSingleObject(finish,5000)==WAIT_OBJECT_0,"client remains alive after pipe EOF");return 0;
}
static fs::Artifact artifact(const mb::Envelope&e){fs::Artifact a{};a.request=e.request;a.bytes={static_cast<unsigned char>(e.request.generation),2,3,4};need(native_storage_read::Sha256(a.bytes.data(),a.bytes.size(),a.sha256),"hash owned diagnostic bytes");auto&r=a.report;r.status=fs::Status::Complete;r.generation=e.request.generation;r.entries=r.exits=r.original_returned=7;r.first_call=1;r.last_call=7;r.save_state=0x10000;r.intents=r.flushed=r.binds=r.queues=r.worker_started=r.worker_joined=r.native_success=r.finalizer_returned=r.return_matched=1;r.phase_mask=31;r.executor_thread=GetCurrentThreadId();r.completed_requests=static_cast<unsigned>(e.request.generation);r.file_bytes_verified=true;return a;}
int wmain(int argc,wchar_t**argv){if(argc>1&&!wcscmp(argv[1],L"--client"))return client(argc,argv);need(argc==2,"host case");SetErrorMode(SEM_FAILCRITICALERRORS|SEM_NOGPFAULTERRORBOX);const std::wstring mode=argv[1];const bool normal=mode==L"normal",claimed=mode.find(L"claimed")!=std::wstring::npos,disconnect=mode.find(L"disconnect")!=std::wstring::npos;
 mb::Mailbox box;retainedMailbox=&box;need(box.Initialize(),"host thread initializes mailbox");mb::Adapter adapter{&box,5000};ownerReport.initialized=ownerReport.armed=1;auto*owner=new a_save_user_owner::Owner;
 SECURITY_ATTRIBUTES sa{sizeof sa,nullptr,TRUE};HANDLE drop=CreateEventW(&sa,TRUE,FALSE,nullptr),closed=CreateEventW(&sa,TRUE,FALSE,nullptr),finish=CreateEventW(&sa,TRUE,FALSE,nullptr),shutdown=CreateEventW(nullptr,TRUE,FALSE,nullptr),serverDone=CreateEventW(nullptr,TRUE,FALSE,nullptr);need(drop&&closed&&finish&&shutdown&&serverDone,"owned events");
 wchar_t name[180]{},exe[2048]{},command[4096]{};swprintf_s(name,L"\\\\.\\pipe\\san14-a-save-%016llx%016llx",static_cast<unsigned long long>(GetCurrentProcessId()),GetTickCount64());need(GetModuleFileNameW(nullptr,exe,2048)>0,"own executable path");swprintf_s(command,L"\"%s\" --client %s %s %lu %llu %llu %llu owned",exe,mode.c_str(),name,GetCurrentProcessId(),reinterpret_cast<unsigned long long>(drop),reinterpret_cast<unsigned long long>(closed),reinterpret_cast<unsigned long long>(finish));
 STARTUPINFOW si{};si.cb=sizeof si;PROCESS_INFORMATION child{};need(CreateProcessW(exe,command,nullptr,nullptr,TRUE,CREATE_NO_WINDOW,nullptr,nullptr,&si,&child),"create only owned client child");CloseHandle(child.hThread);
 ip::Config cfg{};cfg.owner=owner;cfg.pipeName=name;cfg.clientPid=child.dwProcessId;cfg.idleTimeoutMs=3000;cfg.secret[0]=0x5A;cfg.room_id[0]=1;cfg.room_epoch=7;cfg.permit=permit;cfg.submit=mb::Adapter::SubmitPort;cfg.copy=mb::Adapter::CopyPort;cfg.executionContext=&adapter;cfg.executionStop=executionStop;
 ip::Server server;{ip::Server absent;auto bad=cfg;bad.executionStop=nullptr;need(!absent.Open(bad),"stop callback mandatory before owner claim");}need(!ownerReport.stopped,"invalid config never claims owner");need(server.Open(cfg),"actual Server opens authenticated pipe");std::thread service([&]{server.Run(shutdown);SetEvent(serverDone);});
 auto until=GetTickCount64()+10000;bool triggered=false;ULONGLONG cancelledAt=0,elapsed=0;mb::Envelope held{};
 while(GetTickCount64()<until){mb::Report r{};box.Snapshot(r);if(normal){mb::Envelope e;if(box.Take(e)){++hostAccepts;auto a=artifact(e);AcquireSRWLockExclusive(&ownerLock);ownerReport.save=a.report;ReleaseSRWLockExclusive(&ownerLock);need(box.Accept(e)&&box.Complete(e,a),"host business double completes copied artifact");}}
  else if(!triggered&&r.count){need(!r.stopped&&r.records[0].state==mb::State::Queued,"live queued request before fault injection");if(claimed)need(box.Take(held),"host claims before cancellation");triggered=true;cancelledAt=GetTickCount64();if(disconnect){SetEvent(drop);need(WaitForSingleObject(closed,3000)==WAIT_OBJECT_0,"client closed only its pipe");need(WaitForSingleObject(child.hProcess,0)==WAIT_TIMEOUT,"client process remains alive at EOF");}else SetEvent(shutdown);}
  box.Snapshot(r);if(!normal&&triggered&&r.stopped&&!elapsed){elapsed=GetTickCount64()-cancelledAt+1;need(elapsed<1500,"cancelled before five-second Submit deadline");need(r.records[0].state==(claimed?mb::State::Unknown:mb::State::Cancelled),"queued versus claimed cancellation retained");need(!box.Take(held)&&!box.Enqueue(held.request,held.binding),"terminal request cannot be replayed");if(claimed)need(!box.Accept(held),"late host result cannot resurrect cancelled request");}
  if(WaitForSingleObject(serverDone,0)==WAIT_OBJECT_0)break;Sleep(1);
 }
 need(WaitForSingleObject(serverDone,0)==WAIT_OBJECT_0,"server joins without deadlock");service.join();SetEvent(finish);need(WaitForSingleObject(child.hProcess,3000)==WAIT_OBJECT_0,"client exits after explicit release");DWORD childExit=99;need(GetExitCodeProcess(child.hProcess,&childExit)&&!childExit,"client passed");ip::Diagnostics d{};server.Inspect(d);mb::Report r{};box.Snapshot(r);need(d.closed&&d.stopped&&r.stopped&&ownerStops&&!badStopOrder,"mailbox stopped before Owner at every Stop");
 if(normal)need(hostAccepts==2&&d.submits==2&&d.copies==2&&r.count==2&&r.records[0].state==mb::State::Delivered&&r.records[1].state==mb::State::Delivered,"two actual pipe generations fully delivered");else need(triggered&&elapsed&&hostAccepts==0&&d.submits==0&&d.copies==0,"cancelled transaction never accepted or copied");
 printf("{\"case\":\"%ls\",\"passed\":true,\"actual_pipe\":true,\"client_child\":true,\"submits\":%llu,\"copies\":%llu,\"cancellation_ms\":%llu,\"owner_business_double\":true,\"native_save\":false,\"game_access\":false}\n",mode.c_str(),d.submits,d.copies,elapsed);CloseHandle(child.hProcess);CloseHandle(drop);CloseHandle(closed);CloseHandle(finish);CloseHandle(shutdown);CloseHandle(serverDone);return 0;
}
